security:
    access_denied_url: ~

    #access_decision_manager:
        # strategy can be: affirmative, unanimous or consensus
     #   strategy: unanimous

    providers:
        sur_provider:
          id: sur_user_provider


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        sur:
            pattern:  ^/login$
            security: false
        sur_secured:
            pattern:   ^/
            stateless: false
            sur: true
            form_login:
              login_path: /login
            logout:
              path:   /logout
              target: /
              invalidate_session: false #debería ir en true pero se necesita un PHP >= 5.4 para que no falle
              
    access_control:
        - { path: /_wdt/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /_profiler/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
